### ISSUE TITLE
Add testcase for when 0 deposit is needed

### ISSUE THREAD

**Issue by JakeHartnell** [JakeHartnell/cw-dao#13]
Add test to make sure proposals still work when the deposit is configured to zero. There should be no need to set an allowance on the cw20 token.

**Comment by ben2x4** [comment]
Answered this question in the PR, existing tests cover this case, but could be worth it to write an explicit test to document the requirement https://github.com/JakeHartnell/cw-dao/pull/11#discussion_r702476520

**Comment by JakeHartnell** [comment]
This done.
