### ISSUE TITLE
Native token voting

### ISSUE THREAD

**Issue by JakeHartnell** [JakeHartnell/cw-dao#27]
Would be nice to optionally use a native token for voting instead of a cw20.

**Comment by JakeHartnell** [comment]
Do people think this is a good idea?

**Comment by ben2x4** [comment]
hmm, I'm not entirely sure of the use case here. If you want to have a vote with the native token shouldn't you just use the gov module?

**Comment by JakeHartnell** [comment]
Yeah, let's close.
